place:
  registration-secret: "$2y$12$UVJKLcY6xGaH8LpoJw3LOub1UD.qnKd0gXIIdFuXHsevjGjeD35vO"

spring:
  datasource:
    url: jdbc:postgresql://db:5432/map
    username: postgres
    password: qwe
    driver-class-name: org.postgresql.Driver
  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: UTC
  flyway:
    create-schemas: on
springdoc:
  show-actuator: true
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
